#define EST_DOT                             1
#define EST_LP                              2
#define EST_RP                              3
#define EST_AND                             4
#define EST_OR                              5
#define EST_EQ                              6
#define EST_NE                              7
#define EST_GT                              8
#define EST_GE                              9
#define EST_LT                             10
#define EST_LE                             11
#define EST_PLUS                           12
#define EST_MINUS                          13
#define EST_TIMES                          14
#define EST_DIVIDE                         15
#define EST_MOD                            16
#define EST_EXP                            17
#define EST_NOT                            18
#define EST_PLUSPLUS                       19
#define EST_MINUSMINUS                     20
#define EST_ATOM                           21
#define EST_FUNCTION                       22
#define EST_ID                             23
#define EST_EQUALS                         24
#define EST_LBRACE                         25
#define EST_RBRACE                         26
#define EST_SEMICOLON                      27
#define EST_IF                             28
#define EST_ELSE                           29
#define EST_PLUSEQUALS                     30
#define EST_MINUSEQUALS                    31
#define EST_AMPER                          32
#define EST_COMMA                          33
#define EST_INT                            34
#define EST_STRING                         35
#define EST_FLOAT                          36
#define EST_COLON                          37
